FoamFile { version 2.0; format ascii; class dictionary; object optimisationDict; }

// Generic co-optimisation: the coolant path AND the surrounding
// conductive body are decided by ONE design field, while a solid crust under
// the heated surface is pinned and the inlet/outlet plugs are pinned fluid.
//
// minimise   peak temperature on the heated surface  (p-norm surrogate)
// subject to a configured total-pressure-loss cap
//
// Baseline values are generated by the case scripts and are not embedded here

optimisationManager steadyOptimisation;

primalSolvers
{
    op1
    {
        active true; type incompressible; solver thermalSimple;
        thermal
        {
            DFluid  1.0e-5;      // coolant
            DSolid  1.0e-3;      // conductive body (contrast 100)
            Prt     0.85;
            kInterpolation { function BorrvallPetersson; b 20; }
        }
        solutionControls
        {
            nIters 20000;
            consistent true;
            residualControl { "p.*" 1e-8; "U.*" 1e-8; "T.*" 1e-11; }
        }
    }
}

adjointManagers
{
    am1
    {
        primalSolver op1;
        adjointSolvers
        {
            // objective: minimise the peak temperature of the heated surface
            as1
            {
                active true; type incompressible; solver thermalAdjointSimple;
                computeSensitivities true;
                thermal
                {
                    DFluid 1.0e-5; DSolid 1.0e-3; Prt 0.85;
                    couplingSign -1; couplingForm exactFluxTranspose; thermalSensScale 1;
                    kInterpolation { function BorrvallPetersson; b 20; }
                }
                objectives
                {
                    type incompressible;
                    objectiveNames
                    {
                        peakT
                        {
                            weight  1e-6;        // positive = minimise
                            type    patchTemperaturePNorm;
                            patches (heatedSurface);
                            P       8;
                        }
                    }
                }
                ATCModel { ATCModel standard; }
                solutionControls
                {
                    nIters 3000;
                    consistent true;
                    residualControl { "pa.*" 1e-8; "Ua.*" 1e-8; }
                }
            }

        }
    }
}

optimisation
{
    designVariables
    {
        type            topO;
        sensitivityType topO;
        writeAllFields  true;
        writeFieldSens  true;

        // THE POINT OF THIS EXAMPLE ------------------------------------
        // one design field spanning coolant path + conductive body:
        adjointPorousZones   (designSpace);
        // protected crust under the heated surface, and the conductive base:
        fixedPorousZones     (crustZone baseZone);
        fixedPorousValues    (1 1);           // pinned SOLID
        // coolant must always be able to get in and out:
        fixedZeroPorousZones (inletPlug outletPlug);   // pinned FLUID
        // --------------------------------------------------------------

        regularisation
        {
            regularise     true;      // no checkerboard / small-scale porosity
            growFromWalls  false;
            meanRadiusMult 8;
            function       tanh;
            b              20;
        }
        betaMax    2500;
        maxInitChange 0.05;
    }
    updateMethod { method steepestDescent; }
}
